version: '3'

services:

  db:
    image: mysql:8.1
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: ncrawl
      MYSQL_PASSWORD: tmppswd
      MYSQL_DATABASE: crawler
    user: ${UID}:${GID}
    volumes:
     - ./data/mysql:/var/lib/mysql

  crawler:
    image: node-crawler-srv
    build: ./
    depends_on:
     - db
    volumes:
     - ./data:/data
    command:
        crawl
        "--addr=0.0.0.0:40431"
        "--crawler-db=mysql://ncrawl:tmppswd@tcp(db:3306)/crawler"
        "--genesis=/data/mainnet-109331-no-history.g"
      # Make sure you have the GeoLite DB in the ./data directory.
      # Comment out the following two lines to disable the GeoLite DB.
      #- --geoipdb
      #- /data/GeoLite2-Country.mmdb
    ports:
     - 40431:40431

  api:
    image: node-crawler-srv
    build: ./
    depends_on:
     - db
    volumes:
     - ./data:/data
    command:
        api
        "--crawler-db=mysql://ncrawl:tmppswd@tcp(db:3306)/crawler"
        "--api-db=mysql://ncrawl:tmppswd@tcp(db:3306)/crawler"

  frontend:
    image: node-crawler-web
    build: ./frontend
    depends_on:
     - api
    volumes:
     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./data:/data
    ports:
     - 8080:80
