version: '3'

services:
  crawler:
    image: node-crawler-srv
    build: ./
    volumes:
     - ./data:/data
    ports:
     - 40431:40431
    command:
        crawl
        --addr=0.0.0.0:40431
        --timeout=10m
        --crawler-db=/data/crawler.db
        --autovacuum=NONE
        --genesis=/data/mainnet-109331-no-history.g
      # Make sure you have the GeoLite DB in the ./data directory.
      # Comment out the following two lines to disable the GeoLite DB.
      #- --geoipdb
      #- /data/GeoLite2-Country.mmdb

  api:
    image: node-crawler-srv
    build: ./
    volumes:
     - ./data:/data
    depends_on:
     - crawler
    command:
        api
        --crawler-db=/data/crawler.db
        --api-db=/data/api.db

  frontend:
    image: node-crawler-web
    build: ./frontend
    volumes:
     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./data:/data
    depends_on:
     - api
    ports:
     - 8080:80
